version: '3.10'

services:
  api:
    build: .
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    env_file:
      - ./.env
    # environment:
    #   - USER=postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=ttrpg-2023
      - POSTGRES_DB=api_ttrpg
    volumes:
      - postres-db:/var/lib/postgresql/data

volumes:
  postres-db:
