version: '3.10'

services:
  api:
    build: .
    command: bash -c "poetry run alembic upgrade head && postry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      - postgres
    ports: 
      - 8000:8000
    env_file:
      - ./.env
    # environment:
    #   - USER=postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=ttrpg-2023
      - POSTGRES_DB=api_ttrpg
    volumes:
      - postres-db:/var/lib/postgresql/data
      - ./uuid_extension.sql:/docker-entrypoint-initdb.d

volumes:
  postres-db:
