"""add phone number

Revision ID: a2d3ec42c43e
Revises: 26f3f0ff6639
Create Date: 2023-09-04 20:59:54.626848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a2d3ec42c43e"
down_revision: Union[str, None] = "26f3f0ff6639"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column("users", sa.Column("phonenumber", sa.String, nullable=True))
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "phonenumber")
    pass
    # ### end Alembic commands ###
